#ifndef _EVENT_QUEUE_H_
#define _EVENT_QUEUE_H_

/****************************************************
    Event Queue

    File:   event_queue.h
    Author: James Stokebrand
    jamesstokebrand AT gmail DOT com

    event_queue.h file is part of the RGB LED Controller and Node 
     version 1 hardware project.

    This file defines the Event Queue class.  Events are generated by ISRs
     (IE buttons, timers, UART/Comm events etc) and serializes them
     for later use in software state machines.  This queue is ISR safe.
     
    Copyright (C) 2015 - James Stokebrand - 2015 Mar 12

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    Rev History:
     When         Who                Description of change
    -----------  ----------         ------------------------
    2014 Oct 05  James Stokebrand   Initial creation.

*****************************************************/


#ifndef _EVENT_LISTING_H_
#include "event_listing.h"
#endif

#ifndef _OBSERVER_CLASS_H_
#include "observer_class.h"
#endif

#ifndef _STATIC_QUEUE_H_
#include "static_queue.h"
#endif

class EventQueue
: public STATIC_QUEUE_EVENT_LISTING::cqueue
, public EventObserver
{
public:

    EventQueue()
    {}

    virtual ~EventQueue() {}

    virtual void Update(event_element_class const &A)
    {
        // All EventQueue objects will have a event_element_class as a member.
        Enqueue(A);
    }
private:
};

#endif

